apiVersion: apps/v1
kind: Deployment
metadata:
 name: myproject
 labels: 
  app: myproject
spec:
 replicas: 2
 selector:
  matchlabels:
   app: myproject
 template:
  metadata:
   name: mypod
   labels:
    app: myproject
  spec:
   containers:
  - name: myproject
    image: docker.io/botadmin/project1:f9